version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sadhak_app
    restart: always
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn sadhak.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/sadhak_app
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
