# Generated by Django 6.0.2 on 2026-05-14 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expenseitem',
            name='uniq_exp_item_name_per_sub_user_active',
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='item',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.RemoveConstraint(
            model_name='expensemaincategory',
            name='uniq_exp_main_name_per_user_active',
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='main_category',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='main_category',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='expensesubcategory',
            name='uniq_exp_sub_name_per_main_user_active',
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RemoveIndex(
            model_name='expenseentry',
            name='expenses_ex_main_ca_a0be36_idx',
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'main_category', 'sub_category'], name='expenses_ex_user_id_5e984f_idx'),
        ),
        migrations.RemoveField(
            model_name='expensemaincategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expensesubcategory',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='expensesubcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpenseItem',
        ),
        migrations.DeleteModel(
            name='ExpenseMainCategory',
        ),
        migrations.DeleteModel(
            name='ExpenseSubCategory',
        ),
    ]
