# Generated by Django 6.0.2 on 2026-05-17 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expenseitem_uniq_exp_item_name_per_sub_user_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_category', models.CharField(max_length=120)),
                ('sub_category', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rollup_level', models.CharField(choices=[('category', 'Category'), ('subcategory', 'Sub Category'), ('item', 'Item')], default='item', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.budgetplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['user', 'period_type', 'is_active'], name='expenses_bu_user_id_625bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['year', 'month'], name='expenses_bu_year_4eb228_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocationline',
            index=models.Index(fields=['budget_plan', 'main_category', 'sub_category', 'item'], name='expenses_bu_budget__3d1e28_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocationline',
            index=models.Index(fields=['is_active', 'is_deleted'], name='expenses_bu_is_acti_d2c35c_idx'),
        ),
    ]
