# Generated by Django 6.0.2 on 2026-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_budgetplan_budgetallocationline_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='budgetallocation',
            name='expenses_bu_user_id_de07de_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetallocation',
            name='expenses_bu_start_d_81716f_idx',
        ),
        migrations.RemoveField(
            model_name='budgetallocationline',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budgetallocationline',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='BudgetAllocation',
        ),
    ]
