# Generated by Django 6.0.2 on 2026-05-19 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_budgetallocation_expenses_bu_user_id_de07de_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereportpreference',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereportpreference',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseReportDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='expenses.expensereportpreference')),
            ],
            options={
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['preference', 'status'], name='expenses_ex_prefere_622345_idx')],
            },
        ),
    ]
