# Generated by Django 6.0.2 on 2026-05-28 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSyncMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_occurrence_id', models.UUIDField(db_index=True)),
                ('local_parent_type', models.CharField(choices=[('task', 'Task'), ('habit', 'Habit')], max_length=10)),
                ('google_event_id', models.CharField(db_index=True, max_length=255)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_local_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_google_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_event_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'calendar_id', 'google_event_id'), name='uniq_google_event_per_user_calendar'), models.UniqueConstraint(fields=('user', 'local_occurrence_id'), name='uniq_local_occurrence_per_user')],
            },
        ),
        migrations.CreateModel(
            name='GoogleAuthConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('google_sub', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_auth_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='integration_user_id_6b530f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('google_sub', models.CharField(db_index=True, max_length=255)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='integration_user_id_6ce8c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('channel_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('sync_token', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'calendar_id', 'is_active'], name='integration_user_id_bb330c_idx')],
            },
        ),
    ]
