# Generated by Django 6.0.2 on 2026-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_googlecalendarmirrorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsyncmap',
            name='google_etag',
            field=models.CharField(blank=True, help_text="Google's version tag for conflict detection", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsyncmap',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='True if this maps to root event of recurring series'),
        ),
        migrations.AddField(
            model_name='eventsyncmap',
            name='local_task_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Task UUID for recurring root events', null=True),
        ),
        migrations.AddField(
            model_name='eventsyncmap',
            name='recurrence_rule',
            field=models.TextField(blank=True, help_text='RRULE copy for verification', null=True),
        ),
    ]
