# Generated by Django 6.0.2 on 2026-04-08 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overridden', 'Overridden')], default='active', max_length=20)),
                ('override_completed', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overridden', 'Overridden')], default='active', max_length=20)),
                ('override_completed', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('expected_achieved_date', models.DateField()),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tracker.goal')),
            ],
            options={
                'ordering': ('start_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('frequency_type', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('custom', 'Custom')], max_length=20)),
                ('frequency_interval', models.IntegerField(default=1)),
                ('frequency_days', models.JSONField(blank=True, default=list)),
                ('frequency_times_per_period', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency_period', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interval_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_habit', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='tracker.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_habits', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='tracker.milestone')),
            ],
            options={
                'ordering': ('start_date', 'start_time', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('frequency_type', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('custom', 'Custom')], default='once', max_length=20)),
                ('frequency_interval', models.IntegerField(default=1)),
                ('frequency_days', models.JSONField(blank=True, default=list)),
                ('frequency_times_per_period', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency_period', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interval_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_habit', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.goal')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('start_date', 'start_time', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('schedule_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('context_title', models.CharField(blank=True, max_length=255, null=True)),
                ('context_description', models.TextField(blank=True, null=True)),
                ('context_checklist', models.JSONField(blank=True, default=list)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tracker.habit')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tracker.task')),
            ],
            options={
                'ordering': ('scheduled_date', 'scheduled_time', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'section', 'status'], name='tracker_goa_user_id_8c2f15_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['start_date', 'expected_end_date'], name='tracker_goa_start_d_4ab7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'status'], name='tracker_mil_goal_id_e28d26_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['start_date', 'expected_achieved_date'], name='tracker_mil_start_d_29c098_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'status', 'section'], name='tracker_hab_user_id_e3ae60_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['goal', 'milestone'], name='tracker_hab_goal_id_30e891_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['start_date', 'end_date'], name='tracker_hab_start_d_845ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', 'section'], name='tracker_tas_user_id_2da43d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['goal', 'milestone'], name='tracker_tas_goal_id_64e622_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['start_date', 'end_date'], name='tracker_tas_start_d_52ea19_idx'),
        ),
        migrations.AddIndex(
            model_name='taskoccurrence',
            index=models.Index(fields=['task', 'scheduled_date', 'status'], name='tracker_tas_task_id_180837_idx'),
        ),
        migrations.AddIndex(
            model_name='taskoccurrence',
            index=models.Index(fields=['habit', 'scheduled_date', 'status'], name='tracker_tas_habit_i_38a25a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('habit__isnull', True)), models.Q(('task__isnull', True), ('habit__isnull', False)), _connector='OR'), name='tracker_occurrence_single_parent'),
        ),
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('task', 'scheduled_date', 'scheduled_time'), name='tracker_unique_task_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('habit__isnull', False)), fields=('habit', 'scheduled_date', 'scheduled_time'), name='tracker_unique_habit_occurrence'),
        ),
    ]
