# Generated by Django 6.0.2 on 2026-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskoccurrence',
            name='tracker_unique_task_occurrence',
        ),
        migrations.RemoveConstraint(
            model_name='taskoccurrence',
            name='tracker_unique_habit_occurrence',
        ),
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('task__isnull', False)), fields=('task', 'scheduled_date', 'scheduled_time'), name='tracker_unique_task_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('habit__isnull', False), ('is_deleted', False)), fields=('habit', 'scheduled_date', 'scheduled_time'), name='tracker_unique_habit_occurrence'),
        ),
    ]
