# Generated by Django 6.0.2 on 2026-04-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_taskoccurrence_tracker_unique_task_occurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='conflict_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='conflict_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='conflict_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
