# Generated by Django 6.0.2 on 2026-04-16 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_conflict_overridden_at_habit_conflict_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('depends_on_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_edges', to='tracker.habit')),
                ('depends_on_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_edges', to='tracker.task')),
                ('owner_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_edges', to='tracker.habit')),
                ('owner_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_edges', to='tracker.task')),
            ],
            options={
                'indexes': [models.Index(fields=['owner_task', 'is_deleted'], name='tracker_tra_owner_t_221d17_idx'), models.Index(fields=['owner_habit', 'is_deleted'], name='tracker_tra_owner_h_6ee33e_idx'), models.Index(fields=['depends_on_task', 'is_deleted'], name='tracker_tra_depends_a990a8_idx'), models.Index(fields=['depends_on_habit', 'is_deleted'], name='tracker_tra_depends_ece480_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner_task__isnull', False), ('owner_habit__isnull', True)), models.Q(('owner_task__isnull', True), ('owner_habit__isnull', False)), _connector='OR'), name='tracker_dep_single_owner'), models.CheckConstraint(condition=models.Q(models.Q(('depends_on_task__isnull', False), ('depends_on_habit__isnull', True)), models.Q(('depends_on_task__isnull', True), ('depends_on_habit__isnull', False)), _connector='OR'), name='tracker_dep_single_target'), models.CheckConstraint(condition=models.Q(('owner_task', models.F('depends_on_task')), _negated=True), name='tracker_dep_no_task_self'), models.CheckConstraint(condition=models.Q(('owner_habit', models.F('depends_on_habit')), _negated=True), name='tracker_dep_no_habit_self'), models.UniqueConstraint(condition=models.Q(('depends_on_task__isnull', False), ('is_deleted', False), ('owner_task__isnull', False)), fields=('owner_task', 'depends_on_task'), name='tracker_dep_uq_task_task_active'), models.UniqueConstraint(condition=models.Q(('depends_on_habit__isnull', False), ('is_deleted', False), ('owner_task__isnull', False)), fields=('owner_task', 'depends_on_habit'), name='tracker_dep_uq_task_habit_active'), models.UniqueConstraint(condition=models.Q(('depends_on_task__isnull', False), ('is_deleted', False), ('owner_habit__isnull', False)), fields=('owner_habit', 'depends_on_task'), name='tracker_dep_uq_habit_task_active'), models.UniqueConstraint(condition=models.Q(('depends_on_habit__isnull', False), ('is_deleted', False), ('owner_habit__isnull', False)), fields=('owner_habit', 'depends_on_habit'), name='tracker_dep_uq_habit_habit_active')],
            },
        ),
    ]
