# Generated by Django 6.0.2 on 2026-04-18 14:42

import tracker.models.habit
import tracker.models.task
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trackerdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration_config',
            field=models.JSONField(blank=True, default=tracker.models.habit.default_duration_config),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_config',
            field=models.JSONField(blank=True, default=tracker.models.task.default_duration_config),
        ),
    ]
