# Generated by Django 6.0.2 on 2026-04-24 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_habit_duration_config_task_duration_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_mode_all',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_offset',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_mode_all',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_offset',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OccurrenceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('offset_minutes', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('in-app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('event_emitted', models.BooleanField(db_index=True, default=False)),
                ('event_emitted_at', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tracker.taskoccurrence')),
            ],
            options={
                'indexes': [models.Index(fields=['remind_at', 'event_emitted'], name='tracker_occ_remind__df3dea_idx'), models.Index(fields=['sent', 'mode'], name='tracker_occ_sent_aa873f_idx'), models.Index(fields=['occurrence', 'remind_at'], name='tracker_occ_occurre_0b7a72_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('occurrence', 'offset_minutes', 'mode'), name='tracker_unique_occurrence_reminder')],
            },
        ),
    ]
