# Generated by Django 6.0.2 on 2026-05-23 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_habit_reminder_enabled_habit_reminder_mode_all_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='section',
            field=models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth'), ('personal', 'Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='section',
            field=models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth'), ('personal', 'Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth'), ('personal', 'Personal')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('notes', 'Notes'), ('diary', 'Diary')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.CharField(blank=True, choices=[('career', 'Career'), ('health', 'Health'), ('wealth', 'Wealth'), ('personal', 'Personal')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tracker.notes')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DiaryPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_diary_pages', to='tracker.notes')),
            ],
            options={
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('diary_id', 'date'), name='unique_diary_page_date')],
            },
        ),
    ]
