# Generated by Django 6.0.2 on 2026-05-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_goal_section_alter_habit_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reminder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.habit'),
        ),
    ]
