# Generated by Django 6.0.2 on 2026-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_notes_reminder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_google_id',
            field=models.BooleanField(default=False, help_text='True if created in Google Calendar and synced to app'),
        ),
        migrations.AddField(
            model_name='task',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google Calendar root event ID for recurring tasks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.TextField(blank=True, help_text='RRULE format: FREQ=DAILY;UNTIL=20260630;INTERVAL=1', null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for this occurrence', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='google_recurrence_id',
            field=models.CharField(blank=True, help_text='YYYYMMDDTHHMMSS format - identifies which instance of series', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='synced_from_google',
            field=models.BooleanField(default=False, help_text='True if created from Google Calendar event'),
        ),
    ]
