# Generated by Django 6.0.2 on 2026-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_task_external_google_id_task_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='external_google_id',
            field=models.BooleanField(default=False, help_text='True if created in Google Calendar and synced to app'),
        ),
        migrations.AddField(
            model_name='habit',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google Calendar root event ID for recurring habits', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='recurrence_rule',
            field=models.TextField(blank=True, help_text='RRULE format: FREQ=DAILY;UNTIL=20260630;INTERVAL=1', null=True),
        ),
    ]
