# Generated by Django 6.0.2 on 2026-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_habit_external_google_id_habit_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereminder',
            name='google_notification_id',
            field=models.CharField(blank=True, help_text='Google reminder/notification identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occurrencereminder',
            name='synced_to_google',
            field=models.BooleanField(default=False, help_text='True if this reminder has been mirrored to Google Calendar'),
        ),
    ]
